name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest

    permissions:
      # required for softprops/action-gh-release
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: npm ci --ignore-scripts
        # npm run prepare runs the build step for publish and pack
      - run: npm rebuild && npm run prepare
      - run: npm run docs
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: ""
          generate_release_notes: true
          draft: true
          prerelease: false
      - name: action-slack
        uses: 8398a7/action-slack@v3.8.0
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
