name: Push new version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'npm version semver level'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major
        - prerelease
        - prepatch
        - preminor
        - premajor
      # Uncomment the following for text input preId
      # preId:
      #   description: 'Prerelease identifier (required with pre*)'
      #   required: false
      #   type: string
      # Uncomment the following for selection preId
      # preId:
      #   description: 'Prerelease identifier (used with pre*)'
      #   required: true
      #   default: 'beta'
      #   type: choice
      #   options:
      #   - alpha
      #   - beta

jobs:
  # Uncomment the following step if using text input preId
  # validate:
    # name: Validate workflow inputs
    # runs-on: ubuntu-latest

    # steps:
    # - name: Invalid prerelease identifier
      # if: ${{ startsWith(github.event.inputs.version, 'pre') && !github.event.inputs.preId }}
      # run: |
        # echo "Error: 'preId' input is required with 'pre-*' version."
        # exit 1

  version:
    name: Push ${{ inputs.version }} tag
    runs-on: ubuntu-latest

    # Uncomment the following line if using the validate step above
    # needs: [validate]

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
      with:
        # see https://github.com/orgs/community/discussions/25617#discussioncomment-3248494
        token: ${{ secrets.VERSION_TOKEN }}
        # requires contents: write permission for this repo
        # used by `git push` at the end
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Configure git user
      # this step is necessary for `npm version` to succeed
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
    - name: NPM version
      # Uncomment the following line if using preId input
      # run: echo "version=$(npm version ${{ inputs.version }}${{ startsWith(inputs.version, 'pre') && format(' --preid {0}', inputs.preId) || '' }})" >> "$GITHUB_ENV"
      # Uncomment the following line for hardcoded 'beta' preId
      run: echo "version=$(npm version ${{ inputs.version }})${{ startsWith(inputs.version, 'pre') && '--preid beta' || ''}}" >> "$GITHUB_ENV"
    - name: Git push
      run: git push && git push origin ${{ env.version }}
